In [ ]:
# #  запуск всех модулей кроме (НЕ КАНАЮТ ПЕРЕМЕННЫЕ! надо через magic тогда все четка)
# def exec_f(path_exec):
#     with open( path_exec,'r') as exec_f:
#         exec(exec_f.read())
# [ exec_f(j) for j in glob.glob(r"/var/lib/private/**/_ Additions/*", recursive=True) if 'Imports_Formats' not in j];

In [4]:
# magic
############################################################

# magic не запускаются с посмощью run !! поэтому отдельно будут тут! # %magic # посмотреть список magic команд
%matplotlib inline


# run files
%run /home/slebedev/"_Additions"/Imports_Formats.py

%run /home/slebedev/"_Additions"/Connecting_bi_admin.py

%run /home/slebedev/"_Additions"/Date_gen.py

%run /home/slebedev/"_Additions"/xx.py


############################## End ##############################
print( abs_path )

/home/slebedev/

In [5]:
df_date_m['start'][1]
# df_date_m df_date_Y

'2017-02-01'

In [6]:
for i in df_date_Y.iloc[:1,:].values:
        print(f'{i[0]} || {i[1]}')

2017-01-01 || 2017-12-31

In [6]:
qwe.replace('DATE_START_replce', f'{i[0]}').replace('DATE_END_replce', f'{i[1]}')

'\n--/*10.06.2021 ФОН ju (+даты по статусу На складе выдачи)  + тествозвраты*/ 2019-01-13  2021-02-27 \n\n/* В ВОЗВРАТАХ ЧИСТО ТОВАРЫ НЕТ СЕРВИСА И ТД\n * 08.06  ФОН ju + возвраты\t08.06.2021 \n * чист себес, дата с ju, + возвраты\n * \n * */\n\nWITH params AS MATERIALIZED (\nselect\n\n     (2017-01-01 || \' 00:00:00\')::timestamp    frm \n    ,(2017-12-31 || \' 23:59:59\')::timestamp    til\n\t\n)\n\n, \nwarranty_opentech as (\nselect distinct \n-- 751 705 029.15\n-- 180464  2000-01-01 2021-12-31   751 705 029 совпадает (вместе  pa и ww если p.id и distinct)\n-- 751 705 030 (округление) ексель сходится (возвраты динамические суммы меняются но сходимость ДОЛЖНА БЫТЬ!)\n    ww.id_store_item "id принятой по ЗН железяки"   \n\t,p.sum "Сумма возврата"\t\t\t\t\t\t\t\n\t,p.id "id платежа"    \n\n--    ,p.customer_id "p.customer_id (кто платил?)"\n--    ,p.type\n--    ,p.date_po "Дата поступления денег (возврат)"\n--    ,p.purpose "Назначение платежа"\n--    ,ww.number "Номер ЗН"             \n--    ,ww.date_pass "Дата сдачи в сервис"\n--    ,ww.id_payment "ww Платёж, на основании ЗН"\n--    ,p.id as "p.id Платёж, на основании ЗН"\n--    ,ww.date_sold "Дата продажи товара (возвратов)"\n--    ,ww.price_sold\n--    ,ww.id_account_sold "ID Заказа, по которому был продан товар"\n--    ,ww.id_reference_price "Артикул оборудования"\n--    ,ww.fault "Описание неисправности"\n    \n--    ,t.name as "Тип платежа" \n    /*пришлось вырезать "," из "неустойка, штраф", а то таблица ползет*/\n    --    case when position(\',\' in t.name) > 0 then overlay(t.name placing \' \' from position(\',\' in t.name)) else t.name end as "тип платежа" \n--        ,c.id "c.id"\n--        ,c.name "фирма получатель"\n--        ,a.id "Позиции клиентских заказов"\n--        ,a.reference_id "Товарная позиция"\n--        ,a.store_id "Складская позиция, выбранная для продажи"\n--        ,a.id_customer "Плательщик"\n--        ,c.id ",c.id"\n--        ,c.name         as "фирма"\n--        ,ww.\n--        ,*\nfrom params _\ncross join opentech.payments p\n--left join payments.types t on t.id = p.type \nleft join opentech.payments_account pa on p.id = pa.payment_id \nleft join warranty.warranty ww on p.id = ww.id_payment\n--    left join opentech.accounts a on a.id = pa.account_id\n--    left join opentech.customers c on c.id = p.firmid\nwhere \n    p.date_po::date between _.frm and _.til\n    and p.type = payments.type(\'WARRANTY\') -- 6 \n--        and a.state = orders.item_state(\'BUNDLED\')\n--order by 1 --ww.id_store_item\n)\n\n--,params2 as (\n--select\n--    min(wo."Дата продажи товара (возвратов)") frm  \n--    ,max(wo."Дата продажи товара (возвратов)") til\n--    from warranty_opentech wo\n--)\n\n, wares as materialized (\n    select\n        -- a.i as i_log,\n        a.i,\n        a.id as id_order,\n        null::int as id_order_item,\n        a.id_customer as id_customer,\n        a.firm as order_type,\n        a.storage_id as id_storage,\n        a.user_login as order_source,\n        \'Товар\' as type,\n        rp.id as id,\n        rp.name as name,\n        g.name as category,\n        b.name as brand,\n        s.price as price,\n        round(s.cost) as cost,\n        round(s.sprice) as sprice,\n        s.date_sold as date_sold,\n        s.sold as state, \n        coalesce(r.date, checks.created_at) as realization_date,\n        round(s.price * (coalesce(rnds.value, cnds.value, 20) / (100 + coalesce(rnds.value, cnds.value, 20))), 2) as nds,\n        c.name as supplier,\n        u.name as manager\n        ,s.id s_id\n        \n    -- from params _\n    from  opentech.store s\n    join opentech.accounts a on a.store_id = s.id\n    left join opentech.users u on lower(u.login) = lower(a.user_login)\n    left join orders.realization_items_order_items_bindings bi on bi.id_order_item = a.i\n    left join orders.realization_items i on i.id = bi.id_realization_item\n    left join orders.realizations r on r.id = i.id_realization\n    left join payments.order_items_locked_by_check_items il on il.id_order_item = a.i\n    left join payments.check_items ci on ci.id = il.id_check_item_fullpaid\n    left join payments.checks checks on checks.id = ci.id_check\n    left join public.nds rnds on rnds.id = i.id_nds\n    left join public.nds cnds on cnds.code = ci.vat\n    join opentech.reference_price rp on rp.id = s.reference_id\n    left join opentech.section_new sn on sn.id = rp.section_sootv\n    left join catalog.plain_section_list g on g.id = sn.goodid\n    left join catalog.brands b on b.id = rp.brand_id\n    left join opentech.supplyitems si on si.id = s.supplyitemid\n    left join opentech.supplies su on su.id = si.supplyid\n    left join customers.suppliers sup on sup.id_customer = su.supplierid\n    left join opentech.customers c on c.id = coalesce(sup.id_customer_alpha, sup.id_customer)\n    \n    right join warranty_opentech wo on wo."id принятой по ЗН железяки" = s.id\n    \n    where a.state != orders.item_state(\'BUNDLED\')\n        and s.sold != store.item_sold(\'NONE\')\n--        and s.date_sold between _.frm and _.til\n        and s.price > 0\n)\n, bundles as materialized (\n    select\n        -- a.i as i_log,\n        a2.i,\n        a2.id as id_order,          /* id заказа комплекта */\n        a1.id as id_order_item,     /* id заказа комплектующей */\n        a2.id_customer as id_customer,\n        a2.firm as order_type,\n        a2.storage_id as id_storage,\n        a2.user_login as order_source,\n        \'Комплектующая\' as type,\n        rp.id as id,\n        rp.name as name,\n        g.name as category,\n        b.name as brand,\n        s1.price as price,\n        round(s1.cost) as cost,\n        round(s1.sprice) as sprice,\n        s2.date_sold as date_sold,\n        s1.sold as state, \n        coalesce(r.date, checks.created_at) as realization_date,\n        round(s1.price * (coalesce(rnds.value, cnds.value, 20) / (100 + coalesce(rnds.value, cnds.value, 20))), 2) as nds,\n        c.name as supplier,\n        u.name as manager\n        ,s2.id s_id\n\n    -- from params _\n    from  opentech.store s1                            /* складская позиция комплектующей */\n    join opentech.accounts a1 on a1.store_id = s1.id        /* заказ комплектующей */\n    join store.bundled_items bu on bu.id_store_item = s1.id\n    join opentech.store s2 on s2.id = bu.id_bundle          /* складская позиция комплекта */\n    join opentech.accounts a2 on a2.store_id = s2.id        /* заказ комплекта */\n    /* ндс комплектующей */\n    left join orders.realization_items_order_items_bindings bi1 on bi1.id_order_item = a1.i\n    left join orders.realization_items i1 on i1.id = bi1.id_realization_item\n    left join payments.order_items_locked_by_check_items il1 on il1.id_order_item = a1.i\n    left join payments.check_items ci1 on ci1.id = il1.id_check_item_fullpaid\n    left join public.nds rnds on rnds.id = i1.id_nds\n    left join public.nds cnds on cnds.code = ci1.vat\n    /* комплектующая */\n    join opentech.reference_price rp on rp.id = s1.reference_id\n    left join opentech.section_new sn on sn.id = rp.section_sootv\n    left join catalog.plain_section_list g on g.id = sn.goodid\n    left join catalog.brands b on b.id = rp.brand_id\n    /* комплект */    \n    left join opentech.users u on lower(u.login) = lower(a2.user_login)\n    left join orders.realization_items_order_items_bindings bi on bi.id_order_item = a2.i\n    left join orders.realization_items i on i.id = bi.id_realization_item\n    left join orders.realizations r on r.id = i.id_realization\n    left join payments.order_items_locked_by_check_items il on il.id_order_item = a2.i\n    left join payments.check_items ci on ci.id = il.id_check_item_fullpaid\n    left join payments.checks checks on checks.id = ci.id_check\n    left join opentech.supplyitems si on si.id = s2.supplyitemid\n    left join opentech.supplies su on su.id = si.supplyid\n    left join customers.suppliers sup on sup.id_customer = su.supplierid\n    left join opentech.customers c on c.id = coalesce(sup.id_customer_alpha, sup.id_customer)\n    \n    right join warranty_opentech wo on wo."id принятой по ЗН железяки" = s2.id\n    \n    where a1.state = orders.item_state(\'BUNDLED\')\n        and s2.sold != store.item_sold(\'NONE\')\n--        and s2.date_sold between _.frm and _.til\n        and s2.price > 0\n)\n--, services AS MATERIALIZED (\n--    SELECT\n--        -- a.i AS i_log,\n--        a.i,\n--        a.id AS id_order,\n--        null::INT AS id_order_item,\n--        a.id_customer AS id_customer,\n--        a.firm AS order_type,\n--        a.storage_id AS id_storage,\n--        a.user_login AS order_source,\n--        \'Услуга\' AS TYPE,\n--        t.id AS id,\n--        t.name AS name,\n--        c.name AS category,\n--        NULL::TEXT AS brand,\n--        a.price AS price,\n--        NULL::int AS cost,\n--        NULL::int AS sprice,\n--        os.done AS date_sold,\n--        store.item_sold(\'SHIPPED\') AS state,\n--        COALESCE(r.date, checks.created_at) AS realization_date,\n--        ROUND(a.price * (COALESCE(rnds.value, cnds.value, 20) / (100 + COALESCE(rnds.value, cnds.value, 20))), 2) AS nds,\n--        NULL::TEXT AS supplier,\n--        u.name AS manager\n--    -- FROM params _\n--    from  opentech.orderservices os\n--    JOIN opentech.accounts a ON a.i = os.orderitemid\n--    LEFT JOIN opentech.users u ON lower(u.login) = lower(a.user_login)\n--    LEFT JOIN orders.realization_items_order_items_bindings bi ON bi.id_order_item = a.i\n--    LEFT JOIN orders.realization_items i ON i.id = bi.id_realization_item\n--    LEFT JOIN orders.realizations r ON r.id = i.id_realization\n--    LEFT JOIN payments.order_items_locked_by_check_items il ON il.id_order_item = a.i\n--    LEFT JOIN payments.check_items ci ON ci.id = il.id_check_item_fullpaid\n--    LEFT JOIN payments.checks checks ON checks.id = ci.id_check\n--    LEFT JOIN public.nds rnds ON rnds.id = i.id_nds\n--    LEFT JOIN public.nds cnds ON cnds.code = ci.vat\n--    JOIN service.types t ON t.id = os.type\n--    JOIN service.categories c ON c.id = t.id_category\n--    WHERE os.state = service.state(\'SOLD\')\n--        AND os.done BETWEEN _.frm AND _.til\n--        AND a.price > 0\n--), deliveries AS MATERIALIZED (\n--    SELECT\n--        -- a.i AS i_log,\n--        a.i,\n--        a.id AS id_order,\n--        null::INT AS id_order_item,\n--        a.id_customer AS id_customer,\n--        a.firm AS order_type,\n--        a.storage_id AS id_storage,\n--        a.user_login AS order_source,\n--        \'Доставка\' AS TYPE,\n--        d.id AS id,\n--        a.correct_name AS name,\n--        t.name AS category,\n--        NULL::text AS brand,\n--        a.price AS price,\n--        NULL::int AS cost,\n--        NULL::int AS sprice,\n--        d.date AS date_sold,\n--        store.item_sold(\'SHIPPED\') AS state,\n--        COALESCE(r.date, checks.created_at) AS realization_date,\n--        ROUND(a.price * (COALESCE(rnds.value, cnds.value, 20) / (100 + COALESCE(rnds.value, cnds.value, 20))), 2) AS nds,\n--        NULL::text AS supplier,\n--        u.name AS manager\n--    -- FROM params _\n--    from  logistics.deliveries d\n--    JOIN logistics.delivery_types t ON t.id = d.type\n--    JOIN logistics.delivery_items di ON di.id_delivery = d.id\n--    JOIN opentech.accounts a ON a.i = di.id_order_item AND a.correct_name ILIKE \'Доставка%\'\n--    LEFT JOIN opentech.users u ON lower(u.login) = lower(a.user_login)\n--    LEFT JOIN orders.realization_items_order_items_bindings bi ON bi.id_order_item = a.i\n--    LEFT JOIN orders.realization_items i ON i.id = bi.id_realization_item\n--    LEFT JOIN orders.realizations r ON r.id = i.id_realization\n--    LEFT JOIN payments.order_items_locked_by_check_items il ON il.id_order_item = a.i\n--    LEFT JOIN payments.check_items ci ON ci.id = il.id_check_item_fullpaid\n--    LEFT JOIN payments.checks checks ON checks.id = ci.id_check\n--    LEFT JOIN public.nds rnds ON rnds.id = i.id_nds\n--    LEFT JOIN public.nds cnds ON cnds.code = ci.vat\n--    WHERE d.state = logistics.delivery_state(\'CLOSED\')\n--        AND d.date BETWEEN _.frm AND _.til\n--        AND a.price > 0\n--), giftcards AS MATERIALIZED (\n--    SELECT\n--        -- a.i AS i_log,\n--        a.i,\n--        a.id AS id_order,\n--        null::INT AS id_order_item,\n--        a.id_customer AS id_customer,\n--        a.firm AS order_type,\n--        a.storage_id AS id_storage,\n--        a.user_login AS order_source,\n--        \'Подарочная карта\' AS TYPE,\n--        1 AS id,\n--        a.correct_name AS name,\n--        \'Подарочная карта\' AS category,\n--        NULL::text AS brand,\n--        a.price AS price,\n--        NULL::int AS cost,\n--        NULL::int AS sprice,\n--        g.sold_on AS date_sold,\n--        store.item_sold(\'SHIPPED\') AS state,\n--        COALESCE(r.date, checks.created_at) AS realization_date,\n--        ROUND(a.price * (COALESCE(rnds.value, cnds.value, 20) / (100 + COALESCE(rnds.value, cnds.value, 20))), 2) AS nds,\n--        NULL::text AS supplier,\n--        u.name AS manager\n--    -- FROM params _\n--    from  payments.giftcards g\n--    JOIN opentech.accounts a ON a.i = g.id_order_item\n--    LEFT JOIN opentech.users u ON lower(u.login) = lower(a.user_login)\n--    LEFT JOIN orders.realization_items_order_items_bindings bi ON bi.id_order_item = a.i\n--    LEFT JOIN orders.realization_items i ON i.id = bi.id_realization_item\n--    LEFT JOIN orders.realizations r ON r.id = i.id_realization\n--    LEFT JOIN payments.order_items_locked_by_check_items il ON il.id_order_item = a.i\n--    LEFT JOIN payments.check_items ci ON ci.id = il.id_check_item_fullpaid\n--    LEFT JOIN payments.checks checks ON checks.id = ci.id_check\n--    LEFT JOIN public.nds rnds ON rnds.id = i.id_nds\n--    LEFT JOIN public.nds cnds ON cnds.code = ci.vat\n--    WHERE g.status = ANY(payments.giftcard_status(ARRAY[\'ISSUED\', \'EXPENDED\']))\n--        AND g.sold_on BETWEEN _.frm AND _.til\n--        AND a.price > 0\n--)\n, items AS MATERIALIZED (\n    SELECT * FROM wares\n--    UNION ALL SELECT * FROM bundles\n--    UNION ALL SELECT * FROM services\n--    UNION ALL SELECT * FROM deliveries\n--    UNION ALL SELECT * FROM giftcards\n)\n, logistics as materialized (\n    select distinct on (items.id_order)\n        items.id_order,\n        d.type,\n        c.name as freighter,\n        ga.region,\n        ga.city,\n        ga.address\n    from items\n    join logistics.delivery_items di on di.id_order_item = items.i\n    join logistics.deliveries d on d.id = di.id_delivery\n    left join opentech.customers c on c.id = d.id_freighter\n    left join geo.addresses ga on ga.id = d.id_address\n    where d.state = logistics.delivery_state(\'CLOSED\')\n    order by items.id_order, d.date desc\n)\n, customer_managers_log as materialized (\n    /* дата последней отвязки ответственного менеджера */\n    select c.id, max(l._tm)::date unbind_date\n    from opentech.customers c\n    join _logs.opentech__customers l on l.id = c.id\n        and l."_op_type" = 2    /* это запись об изменении карточки */\n        and exist(l._values, \'manager\') /* изменялся ответственный менеджер */\n        and not defined(l._values, \'manager\') /* ответственный менеджер был снят */\n    where c.manager is null\n    group by c.id\n)\n, orders as materialized (\n    select\n        o.id_order,\n        o.order_type,\n        o.date_sold,\n        o.is_full_sold,\n        p.pay_date,\n        o.price = p.pay_sum as is_full_paid,\n        case when m_tender.id_order is not null then \'Т\' end as mark_tender,\n        case when m_request.id_order is not null then \'З\' end as mark_request,\n        case when m_kp.id_order is not null then \'КП\' end as mark_kp\n    from (\n        select\n            i.id_order,\n            min(i.order_type) as order_type,\n            max(i.date_sold)::date as date_sold,\n            sum(i.price) as price,\n            array_agg(distinct i.state) = store.item_sold(array[\'SHIPPED\']) as is_full_sold\n        from items i\n        group by i.id_order\n    ) o\n    left join lateral (\n        select\n            max(p.pay_date)::date as pay_date,\n            sum(\n                case\n                    when p.type = payments.type(\'CASHLESS\') and p.date_out is not null then -pa.sum\n                    else pa.sum\n                end\n            ) as pay_sum\n        from opentech.payments_account pa\n        join opentech.payments p on p.id = pa.payment_id\n        where pa.account_id = o.id_order\n    ) p on true\n    left join orders.marks m_tender on m_tender.id_order = o.id_order and m_tender.id_mark = 1 /*тендер*/\n    left join orders.marks m_request on m_request.id_order = o.id_order and m_request.id_mark = 5 /*запрос цен*/\n    left join orders.marks m_kp on m_kp.id_order = o.id_order and m_kp.id_mark = 6 /*коммерческое предложение*/\n)\n----, profitability as materialized (\n----    /* расчет маржинальности клиентов */\n----    select\n----        id_customer,\n----        case when sum(cost) <> 0 then round(100 * (sum(price) - sum(cost))/ sum(cost)) end as value,\n----        sum(price) - sum(cost) as sum\n----    from items\n----    where not customers.is_special_customer(id_customer)\n----    group by id_customer\n----)\n, logs_date_state as ( \n\t/*\n\t * максимум по дате la._tm (тоесть последнене изменение) для заказа товара если хстор 5 (на складе выдачи)\n\t */\n    select \n        oai.account_id "ID заказа"\n        ,oa.reference_id "Артикул (id товара)"\n        ,max(la._tm)::timestamp             "Дата готовности к выдаче товара"\n        ,to_char(max(la._tm), \'HH24:MI\')     "Время готовности к выдаче товара" -- \'HH24:MI\' "09:14"\n        ,to_char(max(la._tm), \'DD\')         "День готовности к выдаче товара" \n        ,to_char(max(la._tm), \'MM\')         "Месяц готовности к выдаче товара" -- \'TMMonth\' "Января"\n        ,to_char(max(la._tm), \'YYYY\')         "Год готовности к выдаче товара"\n--     ,ois.name "Состояние name"\n--     ,oa.store_id "Складская позиция, выбранная для продажи"\n--     ,oa.state "Состояние позиции заказа"\n--     ,ois.code "Состояние code"\n--     ,max(in_account_date) "Время добавления позиции в заказ"\n--     ,max(acc_date) "Дата создания/оформления заказа"\n--     ,max(fn_date) "Дата реализации"\n    from opentech.accounts oa \n    left join opentech.account_item oai on oai.account_id = oa.id\n    left join orders.item_states ois on ois.id = oa.state\n    left join _logs.opentech__accounts la on la.i = oa.i\n    where \n        la._values::hstore -> \'state\' = \'5\' --5\tRESERVED_ON_STORAGE\tНа складе выдачи\n--     and account_id in( 3752476 ) --"ID заказа"\n--     and account_id not in( 2290882 ) 652503\n--     and reference_id in (652503)\n--     and oa.store_id is null --не нужен !!\n--     and oa.state = 5 --тоже не нужен! (не относится к истории)\n    group by 1,2--,3,4,5,6--,7,8,9\n    order by 1,2--,3,4,5,6--,7,8,9\n)\n, all_end as (\nselect distinct\n\t\n    customer.id "ID клиента",\n    item.manager "ФИО оформившего заказ",\n    COALESCE(customer.name, customer.phone) "Наименование клиента",\n    case when customer.inn is null then \'ФЛ\' else \'ЮЛ\' end "Тип клиента",\n    case\n        when budget.id_customer is not null then \'бюджетник\'\n        when secondhand.id_customer is not null then \'перекуп\'\n        when miner.id_customer is not null then \'майнер\'\n        when transport.id_customer is not null then \'ТК\'\n        when customer.asc = 1 then \'АСЦ\'\n        when customer.concurent = 1 then \'конкурент\'\n    end "Классификация",\n    customer.inn "инн",\n    nullif(customer.respite_period, 0) "Отсрочка, дни",\n    \n    case\n        when o.order_type = orders.type(\'ORGANIZATION\') and o.is_full_paid and o.is_full_sold then\n            nullif(greatest(0, o.pay_date - o.date_sold), 0)\n    end as "Отсрочка факт, дни",\n    \n    ok.id_okved "ОКВ

In [8]:
# for i in df_date_Y.iloc[:1,:].values:
#         print(f'{i[0]} || {i[1]}')
print(f'{i[0]} || {i[1]}')
with psycopg2.connect(dbname=database, user=user, password=password, host=host) as cnxn:
    df = pd.read_sql_query(qwe.replace('DATE_START_replce', f'{i[0]}').replace('DATE_END_replce', f'{i[1]}'), cnxn)

df

DatabaseError: Execution failed on sql '
--/*10.06.2021 ФОН ju (+даты по статусу На складе выдачи)  + тествозвраты*/ 2019-01-13  2021-02-27

/* В ВОЗВРАТАХ ЧИСТО ТОВАРЫ НЕТ СЕРВИСА И ТД
 * 08.06  ФОН ju + возвраты	08.06.2021
 * чист себес, дата с ju, + возвраты
 *
 * */

WITH params AS MATERIALIZED (
select

     (2017-01-01 || ' 00:00:00')::timestamp    frm
    ,(2017-12-31 || ' 23:59:59')::timestamp    til

)

,
warranty_opentech as (
select distinct
-- 751 705 029.15
-- 180464  2000-01-01 2021-12-31   751 705 029 совпадает (вместе  pa и ww если p.id и distinct)
-- 751 705 030 (округление) ексель сходится (возвраты динамические суммы меняются но сходимость ДОЛЖНА БЫТЬ!)
    ww.id_store_item "id принятой по ЗН железяки"
	,p.sum "Сумма возврата"
	,p.id "id платежа"

--    ,p.customer_id "p.customer_id (кто платил?)"
--    ,p.type
--    ,p.date_po "Дата поступления денег (возврат)"
--    ,p.purpose "Назначение платежа"
--    ,ww.number "Номер ЗН"
--    ,ww.date_pass "Дата сдачи в сервис"
--    ,ww.id_payment "ww Платёж, на основании ЗН"
--    ,p.id as "p.id Платёж, на основании ЗН"
--    ,ww.date_sold "Дата продажи товара (возвратов)"
--    ,ww.price_sold
--    ,ww.id_account_sold "ID Заказа, по которому был продан товар"
--    ,ww.id_reference_price "Артикул оборудования"
--    ,ww.fault "Описание неисправности"

--    ,t.name as "Тип платежа"
    /*пришлось вырезать "," из "неустойка, штраф", а то таблица ползет*/
    --    case when position(',' in t.name) > 0 then overlay(t.name placing ' ' from position(',' in t.name)) else t.name end as "тип платежа"
--        ,c.id "c.id"
--        ,c.name "фирма получатель"
--        ,a.id "Позиции клиентских заказов"
--        ,a.reference_id "Товарная позиция"
--        ,a.store_id "Складская позиция, выбранная для продажи"
--        ,a.id_customer "Плательщик"
--        ,c.id ",c.id"
--        ,c.name         as "фирма"
--        ,ww.
--        ,*
from params _
cross join opentech.payments p
--left join payments.types t on t.id = p.type
left join opentech.payments_account pa on p.id = pa.payment_id
left join warranty.warranty ww on p.id = ww.id_payment
--    left join opentech.accounts a on a.id = pa.account_id
--    left join opentech.customers c on c.id = p.firmid
where
    p.date_po::date between _.frm and _.til
    and p.type = payments.type('WARRANTY') -- 6
--        and a.state = orders.item_state('BUNDLED')
--order by 1 --ww.id_store_item
)

--,params2 as (
--select
--    min(wo."Дата продажи товара (возвратов)") frm
--    ,max(wo."Дата продажи товара (возвратов)") til
--    from warranty_opentech wo
--)

, wares as materialized (
    select
        -- a.i as i_log,
        a.i,
        a.id as id_order,
        null::int as id_order_item,
        a.id_customer as id_customer,
        a.firm as order_type,
        a.storage_id as id_storage,
        a.user_login as order_source,
        'Товар' as type,
        rp.id as id,
        rp.name as name,
        g.name as category,
        b.name as brand,
        s.price as price,
        round(s.cost) as cost,
        round(s.sprice) as sprice,
        s.date_sold as date_sold,
        s.sold as state,
        coalesce(r.date, checks.created_at) as realization_date,
        round(s.price * (coalesce(rnds.value, cnds.value, 20) / (100 + coalesce(rnds.value, cnds.value, 20))), 2) as nds,
        c.name as supplier,
        u.name as manager
        ,s.id s_id

    -- from params _
    from  opentech.store s
    join opentech.accounts a on a.store_id = s.id
    left join opentech.users u on lower(u.login) = lower(a.user_login)
    left join orders.realization_items_order_items_bindings bi on bi.id_order_item = a.i
    left join orders.realization_items i on i.id = bi.id_realization_item
    left join orders.realizations r on r.id = i.id_realization
    left join payments.order_items_locked_by_check_items il on il.id_order_item = a.i
    left join payments.check_items ci on ci.id = il.id_check_item_fullpaid
    left join payments.checks checks on checks.id = ci.id_check
    left join public.nds rnds on rnds.id = i.id_nds
    left join public.nds cnds on cnds.code = ci.vat
    join opentech.reference_price rp on rp.id = s.reference_id
    left join opentech.section_new sn on sn.id = rp.section_sootv
    left join catalog.plain_section_list g on g.id = sn.goodid
    left join catalog.brands b on b.id = rp.brand_id
    left join opentech.supplyitems si on si.id = s.supplyitemid
    left join opentech.supplies su on su.id = si.supplyid
    left join customers.suppliers sup on sup.id_customer = su.supplierid
    left join opentech.customers c on c.id = coalesce(sup.id_customer_alpha, sup.id_customer)

    right join warranty_opentech wo on wo."id принятой по ЗН железяки" = s.id

    where a.state != orders.item_state('BUNDLED')
        and s.sold != store.item_sold('NONE')
--        and s.date_sold between _.frm and _.til
        and s.price > 0
)
, bundles as materialized (
    select
        -- a.i as i_log,
        a2.i,
        a2.id as id_order,          /* id заказа комплекта */
        a1.id as id_order_item,     /* id заказа комплектующей */
        a2.id_customer as id_customer,
        a2.firm as order_type,
        a2.storage_id as id_storage,
        a2.user_login as order_source,
        'Комплектующая' as type,
        rp.id as id,
        rp.name as name,
        g.name as category,
        b.name as brand,
        s1.price as price,
        round(s1.cost) as cost,
        round(s1.sprice) as sprice,
        s2.date_sold as date_sold,
        s1.sold as state,
        coalesce(r.date, checks.created_at) as realization_date,
        round(s1.price * (coalesce(rnds.value, cnds.value, 20) / (100 + coalesce(rnds.value, cnds.value, 20))), 2) as nds,
        c.name as supplier,
        u.name as manager
        ,s2.id s_id

    -- from params _
    from  opentech.store s1                            /* складская позиция комплектующей */
    join opentech.accounts a1 on a1.store_id = s1.id        /* заказ комплектующей */
    join store.bundled_items bu on bu.id_store_item = s1.id
    join opentech.store s2 on s2.id = bu.id_bundle          /* складская позиция комплекта */
    join opentech.accounts a2 on a2.store_id = s2.id        /* заказ комплекта */
    /* ндс комплектующей */
    left join orders.realization_items_order_items_bindings bi1 on bi1.id_order_item = a1.i
    left join orders.realization_items i1 on i1.id = bi1.id_realization_item
    left join payments.order_items_locked_by_check_items il1 on il1.id_order_item = a1.i
    left join payments.check_items ci1 on ci1.id = il1.id_check_item_fullpaid
    left join public.nds rnds on rnds.id = i1.id_nds
    left join public.nds cnds on cnds.code = ci1.vat
    /* комплектующая */
    join opentech.reference_price rp on rp.id = s1.reference_id
    left join opentech.section_new sn on sn.id = rp.section_sootv
    left join catalog.plain_section_list g on g.id = sn.goodid
    left join catalog.brands b on b.id = rp.brand_id
    /* комплект */
    left join opentech.users u on lower(u.login) = lower(a2.user_login)
    left join orders.realization_items_order_items_bindings bi on bi.id_order_item = a2.i
    left join orders.realization_items i on i.id = bi.id_realization_item
    left join orders.realizations r on r.id = i.id_realization
    left join payments.order_items_locked_by_check_items il on il.id_order_item = a2.i
    left join payments.check_items ci on ci.id = il.id_check_item_fullpaid
    left join payments.checks checks on checks.id = ci.id_check
    left join opentech.supplyitems si on si.id = s2.supplyitemid
    left join opentech.supplies su on su.id = si.supplyid
    left join customers.suppliers sup on sup.id_customer = su.supplierid
    left join opentech.customers c on c.id = coalesce(sup.id_customer_alpha, sup.id_customer)

    right join warranty_opentech wo on wo."id принятой по ЗН железяки" = s2.id

    where a1.state = orders.item_state('BUNDLED')
        and s2.sold != store.item_sold('NONE')
--        and s2.date_sold between _.frm and _.til
        and s2.price > 0
)
--, services AS MATERIALIZED (
--    SELECT
--        -- a.i AS i_log,
--        a.i,
--        a.id AS id_order,
--        null::INT AS id_order_item,
--        a.id_customer AS id_customer,
--        a.firm AS order_type,
--        a.storage_id AS id_storage,
--        a.user_login AS order_source,
--        'Услуга' AS TYPE,
--        t.id AS id,
--        t.name AS name,
--        c.name AS category,
--        NULL::TEXT AS brand,
--        a.price AS price,
--        NULL::int AS cost,
--        NULL::int AS sprice,
--        os.done AS date_sold,
--        store.item_sold('SHIPPED') AS state,
--        COALESCE(r.date, checks.created_at) AS realization_date,
--        ROUND(a.price * (COALESCE(rnds.value, cnds.value, 20) / (100 + COALESCE(rnds.value, cnds.value, 20))), 2) AS nds,
--        NULL::TEXT AS supplier,
--        u.name AS manager
--    -- FROM params _
--    from  opentech.orderservices os
--    JOIN opentech.accounts a ON a.i = os.orderitemid
--    LEFT JOIN opentech.users u ON lower(u.login) = lower(a.user_login)
--    LEFT JOIN orders.realization_items_order_items_bindings bi ON bi.id_order_item = a.i
--    LEFT JOIN orders.realization_items i ON i.id = bi.id_realization_item
--    LEFT JOIN orders.realizations r ON r.id = i.id_realization
--    LEFT JOIN payments.order_items_locked_by_check_items il ON il.id_order_item = a.i
--    LEFT JOIN payments.check_items ci ON ci.id = il.id_check_item_fullpaid
--    LEFT JOIN payments.checks checks ON checks.id = ci.id_check
--    LEFT JOIN public.nds rnds ON rnds.id = i.id_nds
--    LEFT JOIN public.nds cnds ON cnds.code = ci.vat
--    JOIN service.types t ON t.id = os.type
--    JOIN service.categories c ON c.id = t.id_category
--    WHERE os.state = service.state('SOLD')
--        AND os.done BETWEEN _.frm AND _.til
--        AND a.price > 0
--), deliveries AS MATERIALIZED (
--    SELECT
--        -- a.i AS i_log,
--        a.i,
--        a.id AS id_order,
--        null::INT AS id_order_item,
--        a.id_customer AS id_customer,
--        a.firm AS order_type,
--        a.storage_id AS id_storage,
--        a.user_login AS order_source,
--        'Доставка' AS TYPE,
--        d.id AS id,
--        a.correct_name AS name,
--        t.name AS category,
--        NULL::text AS brand,
--        a.price AS price,
--        NULL::int AS cost,
--        NULL::int AS sprice,
--        d.date AS date_sold,
--        store.item_sold('SHIPPED') AS state,
--        COALESCE(r.date, checks.created_at) AS realization_date,
--        ROUND(a.price * (COALESCE(rnds.value, cnds.value, 20) / (100 + COALESCE(rnds.value, cnds.value, 20))), 2) AS nds,
--        NULL::text AS supplier,
--        u.name AS manager
--    -- FROM params _
--    from  logistics.deliveries d
--    JOIN logistics.delivery_types t ON t.id = d.type
--    JOIN logistics.delivery_items di ON di.id_delivery = d.id
--    JOIN opentech.accounts a ON a.i = di.id_order_item AND a.correct_name ILIKE 'Доставка%'
--    LEFT JOIN opentech.users u ON lower(u.login) = lower(a.user_login)
--    LEFT JOIN orders.realization_items_order_items_bindings bi ON bi.id_order_item = a.i
--    LEFT JOIN orders.realization_items i ON i.id = bi.id_realization_item
--    LEFT JOIN orders.realizations r ON r.id = i.id_realization
--    LEFT JOIN payments.order_items_locked_by_check_items il ON il.id_order_item = a.i
--    LEFT JOIN payments.check_items ci ON ci.id = il.id_check_item_fullpaid
--    LEFT JOIN payments.checks checks ON checks.id = ci.id_check
--    LEFT JOIN public.nds rnds ON rnds.id = i.id_nds
--    LEFT JOIN public.nds cnds ON cnds.code = ci.vat
--    WHERE d.state = logistics.delivery_state('CLOSED')
--        AND d.date BETWEEN _.frm AND _.til
--        AND a.price > 0
--), giftcards AS MATERIALIZED (
--    SELECT
--        -- a.i AS i_log,
--        a.i,
--        a.id AS id_order,
--        null::INT AS id_order_item,
--        a.id_customer AS id_customer,
--        a.firm AS order_type,
--        a.storage_id AS id_storage,
--        a.user_login AS order_source,
--        'Подарочная карта' AS TYPE,
--        1 AS id,
--        a.correct_name AS name,
--        'Подарочная карта' AS category,
--        NULL::text AS brand,
--        a.price AS price,
--        NULL::int AS cost,
--        NULL::int AS sprice,
--        g.sold_on AS date_sold,
--        store.item_sold('SHIPPED') AS state,
--        COALESCE(r.date, checks.created_at) AS realization_date,
--        ROUND(a.price * (COALESCE(rnds.value, cnds.value, 20) / (100 + COALESCE(rnds.value, cnds.value, 20))), 2) AS nds,
--        NULL::text AS supplier,
--        u.name AS manager
--    -- FROM params _
--    from  payments.giftcards g
--    JOIN opentech.accounts a ON a.i = g.id_order_item
--    LEFT JOIN opentech.users u ON lower(u.login) = lower(a.user_login)
--    LEFT JOIN orders.realization_items_order_items_bindings bi ON bi.id_order_item = a.i
--    LEFT JOIN orders.realization_items i ON i.id = bi.id_realization_item
--    LEFT JOIN orders.realizations r ON r.id = i.id_realization
--    LEFT JOIN payments.order_items_locked_by_check_items il ON il.id_order_item = a.i
--    LEFT JOIN payments.check_items ci ON ci.id = il.id_check_item_fullpaid
--    LEFT JOIN payments.checks checks ON checks.id = ci.id_check
--    LEFT JOIN public.nds rnds ON rnds.id = i.id_nds
--    LEFT JOIN public.nds cnds ON cnds.code = ci.vat
--    WHERE g.status = ANY(payments.giftcard_status(ARRAY['ISSUED', 'EXPENDED']))
--        AND g.sold_on BETWEEN _.frm AND _.til
--        AND a.price > 0
--)
, items AS MATERIALIZED (
    SELECT * FROM wares
--    UNION ALL SELECT * FROM bundles
--    UNION ALL SELECT * FROM services
--    UNION ALL SELECT * FROM deliveries
--    UNION ALL SELECT * FROM giftcards
)
, logistics as materialized (
    select distinct on (items.id_order)
        items.id_order,
        d.type,
        c.name as freighter,
        ga.region,
        ga.city,
        ga.address
    from items
    join logistics.delivery_items di on di.id_order_item = items.i
    join logistics.deliveries d on d.id = di.id_delivery
    left join opentech.customers c on c.id = d.id_freighter
    left join geo.addresses ga on ga.id = d.id_address
    where d.state = logistics.delivery_state('CLOSED')
    order by items.id_order, d.date desc
)
, customer_managers_log as materialized (
    /* дата последней отвязки ответственного менеджера */
    select c.id, max(l._tm)::date unbind_date
    from opentech.customers c
    join _logs.opentech__customers l on l.id = c.id
        and l."_op_type" = 2    /* это запись об изменении карточки */
        and exist(l._values, 'manager') /* изменялся ответственный менеджер */
        and not defined(l._values, 'manager') /* ответственный менеджер был снят */
    where c.manager is null
    group by c.id
)
, orders as materialized (
    select
        o.id_order,
        o.order_type,
        o.date_sold,
        o.is_full_sold,
        p.pay_date,
        o.price = p.pay_sum as is_full_paid,
        case when m_tender.id_order is not null then 'Т' end as mark_tender,
        case when m_request.id_order is not null then 'З' end as mark_request,
        case when m_kp.id_order is not null then 'КП' end as mark_kp
    from (
        select
            i.id_order,
            min(i.order_type) as order_type,
            max(i.date_sold)::date as date_sold,
            sum(i.price) as price,
            array_agg(distinct i.state) = store.item_sold(array['SHIPPED']) as is_full_sold
        from items i
        group by i.id_order
    ) o
    left join lateral (
        select
            max(p.pay_date)::date as pay_date,
            sum(
                case
                    when p.type = payments.type('CASHLESS') and p.date_out is not null then -pa.sum
                    else pa.sum
                end
            ) as pay_sum
        from opentech.payments_account pa
        join opentech.payments p on p.id = pa.payment_id
        where pa.account_id = o.id_order
    ) p on true
    left join orders.marks m_tender on m_tender.id_order = o.id_order and m_tender.id_mark = 1 /*тендер*/
    left join orders.marks m_request on m_request.id_order = o.id_order and m_request.id_mark = 5 /*запрос цен*/
    left join orders.marks m_kp on m_kp.id_order = o.id_order and m_kp.id_mark = 6 /*коммерческое предложение*/
)
----, profitability as materialized (
----    /* расчет маржинальности клиентов */
----    select
----        id_customer,
----        case when sum(cost) <> 0 then round(100 * (sum(price) - sum(cost))/ sum(cost)) end as value,
----        sum(price) - sum(cost) as sum
----    from items
----    where not customers.is_special_customer(id_customer)
----    group by id_customer
----)
, logs_date_state as (
	/*
	 * максимум по дате la._tm (тоесть последнене изменение) для заказа товара если хстор 5 (на складе выдачи)
	 */
    select
        oai.account_id "ID заказа"
        ,oa.reference_id "Артикул (id товара)"
        ,max(la._tm)::timestamp             "Дата готовности к выдаче товара"
        ,to_char(max(la._tm), 'HH24:MI')     "Время готовности к выдаче товара" -- 'HH24:MI' "09:14"
        ,to_char(max(la._tm), 'DD')         "День готовности к выдаче товара"
        ,to_char(max(la._tm), 'MM')         "Месяц готовности к выдаче товара" -- 'TMMonth' "Января"
        ,to_char(max(la._tm), 'YYYY')         "Год готовности к выдаче товара"
--     ,ois.name "Состояние name"
--     ,oa.store_id "Складская позиция, выбранная для продажи"
--     ,oa.state "Состояние позиции заказа"
--     ,ois.code "Состояние code"
--     ,max(in_account_date) "Время добавления позиции в заказ"
--     ,max(acc_date) "Дата создания/оформления заказа"
--     ,max(fn_date) "Дата реализации"
    from opentech.accounts oa
    left join opentech.account_item oai on oai.account_id = oa.id
    left join orders.item_states ois on ois.id = oa.state
    left join _logs.opentech__accounts la on la.i = oa.i
    where
        la._values::hstore -> 'state' = '5' --5	RESERVED_ON_STORAGE	На складе выдачи
--     and account_id in( 3752476 ) --"ID заказа"
--     and account_id not in( 2290882 ) 652503
--     and reference_id in (652503)
--     and oa.store_id is null --не нужен !!
--     and oa.state = 5 --тоже не нужен! (не относится к истории)
    group by 1,2--,3,4,5,6--,7,8,9
    order by 1,2--,3,4,5,6--,7,8,9
)
, all_end as (
select distinct

    customer.id "ID клиента",
    item.manager "ФИО оформившего заказ",
    COALESCE(customer.name, customer.phone) "Наименование клиента",
    case when customer.inn is null then 'ФЛ' else 'ЮЛ' end "Тип клиента",
    case
        when budget.id_customer is not null then 'бюджетник'
        when secondhand.id_customer is not null then 'перекуп'
        when miner.id_customer is not null then 'майнер'
        when transport.id_customer is not null then 'ТК'
        when customer.asc = 1 then 'АСЦ'
        when customer.concurent = 1 then 'конкурент'
    end "Классификация",
    customer.inn "инн",
    nullif(customer.respite_period, 0) "Отсрочка, дни",

    case
        when o.order_type = orders.type('ORGANIZATION') and o.is_full_paid and o.is_full_sold then
            nullif(greatest(0, o.pay_date - o.date_sold), 0)
    end as "Отсрочка факт, дни",

    ok.id_okved "ОКВЭД",
    okved_section.name "Отрасль",
    okved.name "Вид деятельности",
    customer_city.name "Город клиента",

--    /*1 + EXTRACT(DAY FROM _.til - customer.registrationdate)::int "Срок жизни клиента",*/
    NULL "Срок жизни клиента",

    manager.name "Ответственный менеджер",

    cml.unbind_date "Дата отвязки менеджера",

--    /*profitability.value "Маржинальность клиента",
--    profitability.sum "Прибыль c клиента",*/
    NULL "Маржинальность клиента",
    NULL "Прибыль c клиента",

    COALESCE(item.id_order_item, ai.account_id) "ID заказа",
    case
        when ai.siteuserid is null then 'Менеджер'

In [18]:
# читаем sql file (и подставляем даты)
path_SQL_warranty_fon = glob.glob( abs_path  + r"SQL_warranty_fon.sql", recursive=True)[0]

with open( path_SQL_warranty_fon, "r", encoding = "utf-8" ) as sql_file:
    
    for i in df_date_Y.iloc[:1,:].values:
        print(f'{i[0]} || {i[1]}')
        sql_query = sql_file.read().replace('DATE_START_replce', f'{i[0]}').replace('DATE_END_replce', f'{i[1]}')
        print( sql_query )
        
        with psycopg2.connect(dbname=database, user=user, password=password, host=host) as cnxn:
            df = pd.read_sql_query(sql_query, cnxn)

df


# sql_file _ SQL query files

2017-01-01 || 2017-12-31
--/*10.06.2021 ФОН ju (+даты по статусу На складе выдачи)  + тествозвраты*/ 2019-01-13  2021-02-27

/* В ВОЗВРАТАХ ЧИСТО ТОВАРЫ НЕТ СЕРВИСА И ТД
 * 08.06  ФОН ju + возвраты    08.06.2021
 * чист себес, дата с ju, + возвраты
 *
 * */

WITH params AS MATERIALIZED (
select

    ( '2017-01-01' || ' 00:00:00')::timestamp    frm
    ,( '2017-12-31' || ' 23:59:59')::timestamp    til

)

,
warranty_opentech as (
select distinct
-- 751 705 029.15
-- 180464  2000-01-01 2021-12-31   751 705 029 совпадает (вместе  pa и ww если p.id и distinct)
-- 751 705 030 (округление) ексель сходится (возвраты динамические суммы меняются но сходимость ДОЛЖНА БЫТЬ!)
    ww.id_store_item "id принятой по ЗН железяки"
    ,p.sum "Сумма возврата"
    ,p.id "id платежа"

--    ,p.customer_id "p.customer_id (кто платил?)"
--    ,p.type
--    ,p.date_po "Дата поступления денег (возврат)"
--    ,p.purpose "Назначение платежа"
--    ,ww.number "Номер ЗН"

--    ,ww.date_pass "Дата сдачи в сервис"
--    ,ww.id_payment "ww Платёж, на основании ЗН"
--    ,p.id as "p.id Платёж, на основании ЗН"
--    ,ww.date_sold "Дата продажи товара (возвратов)"
--    ,ww.price_sold
--    ,ww.id_account_sold "ID Заказа, по которому был продан товар"
--    ,ww.id_reference_price "Артикул оборудования"
--    ,ww.fault "Описание неисправности"

--    ,t.name as "Тип платежа"
    /*пришлось вырезать "," из "неустойка, штраф", а то таблица ползет*/
    --    case when position(',' in t.name) > 0 then overlay(t.name placing ' ' from position(',' in t.name)) else t.name end as "тип платежа"
--        ,c.id "c.id"
--        ,c.name "фирма получатель"
--        ,a.id "Позиции клиентских заказов"
--        ,a.reference_id "Товарная позиция"
--        ,a.store_id "Складская позиция, выбранная для продажи"
--        ,a.id_customer "Плательщик"
--        ,c.id ",c.id"
--        ,c.name         as "фирма"
--        ,ww.
--        ,*
from params _
cross join opentech.payments p
--left join payments.types t on t.id = p.type
left join opentech.payments_account pa on p.id = pa.payment_id
left join warranty.warranty ww on p.id = ww.id_payment
--    left join opentech.accounts a on a.id = pa.account_id
--    left join opentech.customers c on c.id = p.firmid
where
    p.date_po::date between _.frm and _.til
    and p.type = payments.type('WARRANTY') -- 6
--        and a.state = orders.item_state('BUNDLED')
--order by 1 --ww.id_store_item
)

--,params2 as (
--select
--    min(wo."Дата продажи товара (возвратов)") frm
--    ,max(wo."Дата продажи товара (возвратов)") til
--    from warranty_opentech wo
--)

, wares as materialized (
    select
        -- a.i as i_log,
        a.i,
        a.id as id_order,
        null::int as id_order_item,
        a.id_customer as id_customer,
        a.firm as order_type,
        a.storage_id as id_storage,
        a.user_login as order_source,
        'Товар' as type,
        rp.id as id,
        rp.name as name,
        g.name as category,
        b.name as brand,
        s.price as price,
        round(s.cost) as cost,
        round(s.sprice) as sprice,
        s.date_sold as date_sold,
        s.sold as state,
        coalesce(r.date, checks.created_at) as realization_date,
        round(s.price * (coalesce(rnds.value, cnds.value, 20) / (100 + coalesce(rnds.value, cnds.value, 20))), 2) as nds,
        c.name as supplier,
        u.name as manager
        ,s.id s_id

    -- from params _
    from  opentech.store s
    join opentech.accounts a on a.store_id = s.id
    left join opentech.users u on lower(u.login) = lower(a.user_login)
    left join orders.realization_items_order_items_bindings bi on bi.id_order_item = a.i
    left join orders.realization_items i on i.id = bi.id_realization_item
    left join orders.realizations r on r.id = i.id_realization
    left join payments.order_items_locked_by_check_items il on il.id_order_item = a.i
    left join payments.check_items ci on ci.id = il.id_check_item_fullpaid
    left join payments.checks checks on checks.id = ci.id_check
    left join public.nds rnds on rnds.id = i.id_nds
    left join public.nds cnds on cnds.code = ci.vat
    join opentech.reference_price rp on rp.id = s.reference_id
    left join opentech.section_new sn on sn.id = rp.section_sootv
    left join catalog.plain_section_list g on g.id = sn.goodid
    left join catalog.brands b on b.id = rp.brand_id
    left join opentech.supplyitems si on si.id = s.supplyitemid
    left join opentech.supplies su on su.id = si.supplyid
    left join customers.suppliers sup on sup.id_customer = su.supplierid
    left join opentech.customers c on c.id = coalesce(sup.id_customer_alpha, sup.id_customer)

    right join warranty_opentech wo on wo."id принятой по ЗН железяки" = s.id

    where a.state != orders.item_state('BUNDLED')
        and s.sold != store.item_sold('NONE')
--        and s.date_sold between _.frm and _.til
        and s.price > 0
)
, bundles as materialized (
    select
        -- a.i as i_log,
        a2.i,
        a2.id as id_order,          /* id заказа комплекта */
        a1.id as id_order_item,     /* id заказа комплектующей */
        a2.id_customer as id_customer,
        a2.firm as order_type,
        a2.storage_id as id_storage,
        a2.user_login as order_source,
        'Комплектующая' as type,
        rp.id as id,
        rp.name as name,
        g.name as category,
        b.name as brand,
        s1.price as price,
        round(s1.cost) as cost,
        round(s1.sprice) as sprice,
        s2.date_sold as date_sold,
        s1.sold as state,
        coalesce(r.date, checks.created_at) as realization_date,
        round(s1.price * (coalesce(rnds.value, cnds.value, 20) / (100 + coalesce(rnds.value, cnds.value, 20))), 2) as nds,
        c.name as supplier,
        u.name as manager
        ,s2.id s_id

    -- from params _
    from  opentech.store s1                            /* складская позиция комплектующей */
    join opentech.accounts a1 on a1.store_id = s1.id        /* заказ комплектующей */
    join store.bundled_items bu on bu.id_store_item = s1.id
    join opentech.store s2 on s2.id = bu.id_bundle          /* складская позиция комплекта */
    join opentech.accounts a2 on a2.store_id = s2.id        /* заказ комплекта */
    /* ндс комплектующей */
    left join orders.realization_items_order_items_bindings bi1 on bi1.id_order_item = a1.i
    left join orders.realization_items i1 on i1.id = bi1.id_realization_item
    left join payments.order_items_locked_by_check_items il1 on il1.id_order_item = a1.i
    left join payments.check_items ci1 on ci1.id = il1.id_check_item_fullpaid
    left join public.nds rnds on rnds.id = i1.id_nds
    left join public.nds cnds on cnds.code = ci1.vat
    /* комплектующая */
    join opentech.reference_price rp on rp.id = s1.reference_id
    left join opentech.section_new sn on sn.id = rp.section_sootv
    left join catalog.plain_section_list g on g.id = sn.goodid
    left join catalog.brands b on b.id = rp.brand_id
    /* комплект */
    left join opentech.users u on lower(u.login) = lower(a2.user_login)
    left join orders.realization_items_order_items_bindings bi on bi.id_order_item = a2.i
    left join orders.realization_items i on i.id = bi.id_realization_item
    left join orders.realizations r on r.id = i.id_realization
    left join payments.order_items_locked_by_check_items il on il.id_order_item = a2.i
    left join payments.check_items ci on ci.id = il.id_check_item_fullpaid
    left join payments.checks checks on checks.id = ci.id_check
    left join opentech.supplyitems si on si.id = s2.supplyitemid
    left join opentech.supplies su on su.id = si.supplyid
    left join customers.suppliers sup on sup.id_customer = su.supplierid
    left join opentech.customers c on c.id = coalesce(sup.id_customer_alpha, sup.id_customer)

    right join warranty_opentech wo on wo."id принятой по ЗН железяки" = s2.id

    where a1.state = orders.item_state('BUNDLED')
        and s2.sold != store.item_sold('NONE')
--        and s2.date_sold between _.frm and _.til
        and s2.price > 0
)
--, services AS MATERIALIZED (
--    SELECT
--        -- a.i AS i_log,
--        a.i,
--        a.id AS id_order,
--        null::INT AS id_order_item,
--        a.id_customer AS id_customer,
--        a.firm AS order_type,
--        a.storage_id AS id_storage,
--        a.user_login AS order_source,
--        'Услуга' AS TYPE,
--        t.id AS id,
--        t.name AS name,
--        c.name AS category,
--        NULL::TEXT AS brand,
--        a.price AS price,
--        NULL::int AS cost,
--        NULL::int AS sprice,
--        os.done AS date_sold,
--        store.item_sold('SHIPPED') AS state,
--        COALESCE(r.date, checks.created_at) AS realization_date,
--        ROUND(a.price * (COALESCE(rnds.value, cnds.value, 20) / (100 + COALESCE(rnds.value, cnds.value, 20))), 2) AS nds,
--        NULL::TEXT AS supplier,
--        u.name AS manager
--    -- FROM params _
--    from  opentech.orderservices os
--    JOIN opentech.accounts a ON a.i = os.orderitemid
--    LEFT JOIN opentech.users u ON lower(u.login) = lower(a.user_login)
--    LEFT JOIN orders.realization_items_order_items_bindings bi ON bi.id_order_item = a.i
--    LEFT JOIN orders.realization_items i ON i.id = bi.id_realization_item
--    LEFT JOIN orders.realizations r ON r.id = i.id_realization
--    LEFT JOIN payments.order_items_locked_by_check_items il ON il.id_order_item = a.i
--    LEFT JOIN payments.check_items ci ON ci.id = il.id_check_item_fullpaid
--    LEFT JOIN payments.checks checks ON checks.id = ci.id_check
--    LEFT JOIN public.nds rnds ON rnds.id = i.id_nds
--    LEFT JOIN public.nds cnds ON cnds.code = ci.vat
--    JOIN service.types t ON t.id = os.type
--    JOIN service.categories c ON c.id = t.id_category
--    WHERE os.state = service.state('SOLD')
--        AND os.done BETWEEN _.frm AND _.til
--        AND a.price > 0
--), deliveries AS MATERIALIZED (
--    SELECT
--        -- a.i AS i_log,
--        a.i,
--        a.id AS id_order,
--        null::INT AS id_order_item,
--        a.id_customer AS id_customer,
--        a.firm AS order_type,
--        a.storage_id AS id_storage,
--        a.user_login AS order_source,
--        'Доставка' AS TYPE,
--        d.id AS id,
--        a.correct_name AS name,
--        t.name AS category,
--        NULL::text AS brand,
--        a.price AS price,
--        NULL::int AS cost,
--        NULL::int AS sprice,
--        d.date AS date_sold,
--        store.item_sold('SHIPPED') AS state,
--        COALESCE(r.date, checks.created_at) AS realization_date,
--        ROUND(a.price * (COALESCE(rnds.value, cnds.value, 20) / (100 + COALESCE(rnds.value, cnds.value, 20))), 2) AS nds,
--        NULL::text AS supplier,
--        u.name AS manager
--    -- FROM params _
--    from  logistics.deliveries d
--    JOIN logistics.delivery_types t ON t.id = d.type
--    JOIN logistics.delivery_items di ON di.id_delivery = d.id
--    JOIN opentech.accounts a ON a.i = di.id_order_item AND a.correct_name ILIKE 'Доставка%'
--    LEFT JOIN opentech.users u ON lower(u.login) = lower(a.user_login)
--    LEFT JOIN orders.realization_items_order_items_bindings bi ON bi.id_order_item = a.i
--    LEFT JOIN orders.realization_items i ON i.id = bi.id_realization_item
--    LEFT JOIN orders.realizations r ON r.id = i.id_realization
--    LEFT JOIN payments.order_items_locked_by_check_items il ON il.id_order_item = a.i
--    LEFT JOIN payments.check_items ci ON ci.id = il.id_check_item_fullpaid
--    LEFT JOIN payments.checks checks ON checks.id = ci.id_check
--    LEFT JOIN public.nds rnds ON rnds.id = i.id_nds
--    LEFT JOIN public.nds cnds ON cnds.code = ci.vat
--    WHERE d.state = logistics.delivery_state('CLOSED')
--        AND d.date BETWEEN _.frm AND _.til
--        AND a.price > 0
--), giftcards AS MATERIALIZED (
--    SELECT
--        -- a.i AS i_log,
--        a.i,
--        a.id AS id_order,
--        null::INT AS id_order_item,
--        a.id_customer AS id_customer,
--        a.firm AS order_type,
--        a.storage_id AS id_storage,
--        a.user_login AS order_source,
--        'Подарочная карта' AS TYPE,
--        1 AS id,
--        a.correct_name AS name,
--        'Подарочная карта' AS category,
--        NULL::text AS brand,
--        a.price AS price,
--        NULL::int AS cost,
--        NULL::int AS sprice,
--        g.sold_on AS date_sold,
--        store.item_sold('SHIPPED') AS state,
--        COALESCE(r.date, checks.created_at) AS realization_date,
--        ROUND(a.price * (COALESCE(rnds.value, cnds.value, 20) / (100 + COALESCE(rnds.value, cnds.value, 20))), 2) AS nds,
--        NULL::text AS supplier,
--        u.name AS manager
--    -- FROM params _
--    from  payments.giftcards g
--    JOIN opentech.accounts a ON a.i = g.id_order_item
--    LEFT JOIN opentech.users u ON lower(u.login) = lower(a.user_login)
--    LEFT JOIN orders.realization_items_order_items_bindings bi ON bi.id_order_item = a.i
--    LEFT JOIN orders.realization_items i ON i.id = bi.id_realization_item
--    LEFT JOIN orders.realizations r ON r.id = i.id_realization
--    LEFT JOIN payments.order_items_locked_by_check_items il ON il.id_order_item = a.i
--    LEFT JOIN payments.check_items ci ON ci.id = il.id_check_item_fullpaid
--    LEFT JOIN payments.checks checks ON checks.id = ci.id_check
--    LEFT JOIN public.nds rnds ON rnds.id = i.id_nds
--    LEFT JOIN public.nds cnds ON cnds.code = ci.vat
--    WHERE g.status = ANY(payments.giftcard_status(ARRAY['ISSUED', 'EXPENDED']))
--        AND g.sold_on BETWEEN _.frm AND _.til
--        AND a.price > 0
--)
, items AS MATERIALIZED (
    SELECT * FROM wares
--    UNION ALL SELECT * FROM bundles
--    UNION ALL SELECT * FROM services
--    UNION ALL SELECT * FROM deliveries
--    UNION ALL SELECT * FROM giftcards
)
, logistics as materialized (
    select distinct on (items.id_order)
        items.id_order,
        d.type,
        c.name as freighter,
        ga.region,
        ga.city,
        ga.address
    from items
    join logistics.delivery_items di on di.id_order_item = items.i
    join logistics.deliveries d on d.id = di.id_delivery
    left join opentech.customers c on c.id = d.id_freighter
    left join geo.addresses ga on ga.id = d.id_address
    where d.state = logistics.delivery_state('CLOSED')
    order by items.id_order, d.date desc
)
, customer_managers_log as materialized (
    /* дата последней отвязки ответственного менеджера */
    select c.id, max(l._tm)::date unbind_date
    from opentech.customers c
    join _logs.opentech__customers l on l.id = c.id
        and l."_op_type" = 2    /* это запись об изменении карточки */
        and exist(l._values, 'manager') /* изменялся ответственный менеджер */
        and not defined(l._values, 'manager') /* ответственный менеджер был снят */
    where c.manager is null
    group by c.id
)
, orders as materialized (
    select
        o.id_order,
        o.order_type,
        o.date_sold,
        o.is_full_sold,
        p.pay_date,
        o.price = p.pay_sum as is_full_paid,
        case when m_tender.id_order is not null then 'Т' end as mark_tender,
        case when m_request.id_order is not null then 'З' end as mark_request,
        case when m_kp.id_order is not null then 'КП' end as mark_kp
    from (
        select
            i.id_order,
            min(i.order_type) as order_type,
            max(i.date_sold)::date as date_sold,
            sum(i.price) as price,
            array_agg(distinct i.state) = store.item_sold(array['SHIPPED']) as is_full_sold
        from items i
        group by i.id_order
    ) o
    left join lateral (
        select
            max(p.pay_date)::date as pay_date,
            sum(
                case
                    when p.type = payments.type('CASHLESS') and p.date_out is not null then -pa.sum
                    else pa.sum
                end
            ) as pay_sum
        from opentech.payments_account pa
        join opentech.payments p on p.id = pa.payment_id
        where pa.account_id = o.id_order
    ) p on true
    left join orders.marks m_tender on m_tender.id_order = o.id_order and m_tender.id_mark = 1 /*тендер*/
    left join orders.marks m_request on m_request.id_order = o.id_order and m_request.id_mark = 5 /*запрос цен*/
    left join orders.marks m_kp on m_kp.id_order = o.id_order and m_kp.id_mark = 6 /*коммерческое предложение*/
)
----, profitability as materialized (
----    /* расчет маржинальности клиентов */
----    select
----        id_customer,
----        case when sum(cost) <> 0 then round(100 * (sum(price) - sum(cost))/ sum(cost)) end as value,
----        sum(price) - sum(cost) as sum
----    from items
----    where not customers.is_special_customer(id_customer)
----    group by id_customer
----)
, logs_date_state as (
    /*
     * максимум по дате la._tm (тоесть последнене изменение) для заказа товара если хстор 5 (на складе выдачи)
     */
    select
        oai.account_id "ID заказа"
        ,oa.reference_id "Артикул (id товара)"
        ,max(la._tm)::timestamp             "Дата готовности к выдаче товара"
        ,to_char(max(la._tm), 'HH24:MI')     "Время готовности к выдаче товара" -- 'HH24:MI' "09:14"
        ,to_char(max(la._tm), 'DD')         "День готовности к выдаче товара"
        ,to_char(max(la._tm), 'MM')         "Месяц готовности к выдаче товара" -- 'TMMonth' "Января"
        ,to_char(max(la._tm), 'YYYY')         "Год готовности к выдаче товара"
--     ,ois.name "Состояние name"
--     ,oa.store_id "Складская позиция, выбранная для продажи"
--     ,oa.state "Состояние позиции заказа"
--     ,ois.code "Состояние code"
--     ,max(in_account_date) "Время добавления позиции в заказ"
--     ,max(acc_date) "Дата создания/оформления заказа"
--     ,max(fn_date) "Дата реализации"
    from opentech.accounts oa
    left join opentech.account_item oai on oai.account_id = oa.id
    left join orders.item_states ois on ois.id = oa.state
    left join _logs.opentech__accounts la on la.i = oa.i
    where
        la._values::hstore -> 'state' = '5' --5    RESERVED_ON_STORAGE    На складе выдачи
--     and account_id in( 3752476 ) --"ID заказа"
--     and account_id not in( 2290882 ) 652503
--     and reference_id in (652503)
--     and oa.store_id is null --не нужен !!
--     and oa.state = 5 --тоже не нужен! (не относится к истории)
    group by 1,2--,3,4,5,6--,7,8,9
    order by 1,2--,3,4,5,6--,7,8,9
)
, all_end as (
select distinct

    customer.id "ID клиента",
    item.manager "ФИО оформившего заказ",
    COALESCE(customer.name, customer.phone) "Наименование клиента",
    case when customer.inn is null then 'ФЛ' else 'ЮЛ' end "Тип клиента",
    case
        when budget.id_customer is not null then 'бюджетник'
        when secondhand.id_customer is not null then 'перекуп'
        when miner.id_customer is not null then 'майнер'
        when transport.id_customer is not null then 'ТК'
        when customer.asc = 1 then 'АСЦ'
        when customer.concurent = 1 then 'конкурент'
    end "Классификация",
    customer.inn "инн",
    nullif(customer.respite_period, 0) "Отсрочка, дни",

    case
        when o.order_type = orders.type('ORGANIZATION') and o.is_full_paid and o.is_full_sold then
            nullif(greatest(0, o.pay_date - o.date_sold), 0)
    end as "Отсрочка факт, дни",

    ok.id_okved "ОКВЭД",
    okved_section.name "Отрасль",
    okved.name "Вид деятельности",
    customer_city.name "Город клиента",

--    /*1 + EXTRACT(DAY FROM _.til - customer.registrationdate)::int "Срок жизни клиента",*/
    NULL "Срок жизни клиента",

    manager.name "Ответственный менеджер",

    cml.unbind_date "Дата отвязки менеджера",

--    /*profitability.value "Маржинальность клиента",
--    profitability.sum "Прибыль c клиента",*/
    NULL "Маржинальность клиента",
    NULL "Прибыль c клиента",

    COALESCE(item.id_order_item, ai.account_id) "ID заказа",
    case

,ID клиента,ФИО оформившего заказ,Наименование клиента,Тип клиента,Классификация,инн,"Отсрочка, дни","Отсрочка факт, дни",ОКВЭД,Отрасль,...,Дата готовности к выдаче товара,Время готовности к выдаче товара,День готовности к выдаче товара,Месяц готовности к выдаче товара,Год готовности к выдаче товара,id товара находящийся на складе,id принятой по ЗН железяки,case,id платежа,Сумма возврата
0,1.00,Азгалдян А.Ю.,частное лицо,ФЛ,None,None,nan,nan,None,None,...,NaT,None,None,None,None,6847221.00,6847221.00,=,2938869,120
1,1.00,Азгалдян А.Ю.,частное лицо,ФЛ,None,None,nan,nan,None,None,...,NaT,None,None,None,None,7634309.00,7634309.00,=,2540369,211
2,1.00,Алеев Ф. Р.,частное лицо,ФЛ,None,None,nan,nan,None,None,...,NaT,None,None,None,None,5139497.00,5139497.00,=,2652213,400
3,1.00,Арбузов Д. Ю.,частное лицо,ФЛ,None,None,nan,nan,None,None,...,2017-06-15 20:15:53.966556,20:15,15,06,2017,8008211.00,8008211.00,=,2692887,10990
4,1.00,Бабешко А. В.,частное лицо,ФЛ,None,None,nan,nan,None,None,...,NaT,None,None,None,None,5899484.00,5899484.00,=,2661401,3620
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23297,nan,None,None,ФЛ,None,None,nan,nan,None,None,...,NaT,None,None,None,None,nan,8591510.00,not,2863953,637
23298,nan,None,None,ФЛ,None,None,nan,nan,None,None,...,NaT,None,None,None,None,nan,8591537.00,not,2863947,637
23299,nan,None,None,ФЛ,None,None,nan,nan,None,None,...,NaT,None,None,None,None,nan,8591541.00,not,2863936,637
23300,nan,None,None,ФЛ,None,None,nan,nan,None,None,...,NaT,None,None,None,None,nan,nan,not,2537680,500
23301,nan,None,None,ФЛ,None,None,nan,nan,None,None,...,NaT,None,None,None,None,nan,nan,not,2936976,2800

In [27]:
df

,ID клиента,ФИО оформившего заказ,Наименование клиента,Тип клиента,Классификация,инн,"Отсрочка, дни","Отсрочка факт, дни",ОКВЭД,Отрасль,...,Дата готовности к выдаче товара,Время готовности к выдаче товара,День готовности к выдаче товара,Месяц готовности к выдаче товара,Год готовности к выдаче товара,id товара находящийся на складе,id принятой по ЗН железяки,case,id платежа,Сумма возврата
0,1.00,Азгалдян А.Ю.,частное лицо,ФЛ,None,None,nan,nan,None,None,...,NaT,None,None,None,None,6847221.00,6847221.00,=,2938869,120
1,1.00,Азгалдян А.Ю.,частное лицо,ФЛ,None,None,nan,nan,None,None,...,NaT,None,None,None,None,7634309.00,7634309.00,=,2540369,211
2,1.00,Алеев Ф. Р.,частное лицо,ФЛ,None,None,nan,nan,None,None,...,NaT,None,None,None,None,5139497.00,5139497.00,=,2652213,400
3,1.00,Арбузов Д. Ю.,частное лицо,ФЛ,None,None,nan,nan,None,None,...,2017-06-15 20:15:53.966556,20:15,15,06,2017,8008211.00,8008211.00,=,2692887,10990
4,1.00,Бабешко А. В.,частное лицо,ФЛ,None,None,nan,nan,None,None,...,NaT,None,None,None,None,5899484.00,5899484.00,=,2661401,3620
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23297,nan,None,None,ФЛ,None,None,nan,nan,None,None,...,NaT,None,None,None,None,nan,8591510.00,not,2863953,637
23298,nan,None,None,ФЛ,None,None,nan,nan,None,None,...,NaT,None,None,None,None,nan,8591537.00,not,2863947,637
23299,nan,None,None,ФЛ,None,None,nan,nan,None,None,...,NaT,None,None,None,None,nan,8591541.00,not,2863936,637
23300,nan,None,None,ФЛ,None,None,nan,nan,None,None,...,NaT,None,None,None,None,nan,nan,not,2537680,500
23301,nan,None,None,ФЛ,None,None,nan,nan,None,None,...,NaT,None,None,None,None,nan,nan,not,2936976,2800

10.598588585853577

In [28]:
# to_csv
df.to_csv(abs_path + r'_ DATA/' + 'warranty.csv', sep='☺',  index=False) # cp-1251 encoding='UTF-8', engine='xlsxwriter'

In [25]:
glob.glob( abs_path + r"**/"  + r"SQL_warranty_fon.sql", recursive=True)[0]

'/home/slebedev/_  SQL query files/SQL_warranty_fon.sql'

In [26]:
abs_path

'/home/slebedev/'

In [1]:
2+2

4

In [2]:
print('stfjhsrt')

stfjhsrt